name: Java CI

on:
  push:
    branches: [ challenge-weatherdata-solution, challenge-weatherdata-dev ]
  pull_request:
    branches: [ challenge-weatherdata-solution ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean verify
